// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouHnDlRq6UHVcfu67JqsHTXePohr1dDY',
    appId: '1:487120249063:web:6e54e6972560d11a9c8242',
    messagingSenderId: '487120249063',
    projectId: 'iedcwebsite-6a1fc',
    authDomain: 'iedcwebsite-6a1fc.firebaseapp.com',
    storageBucket: 'iedcwebsite-6a1fc.firebasestorage.app',
    measurementId: 'G-PKXXSF07H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFuNifilgKzKwYmg9bPYVv_8R_lgn-tsY',
    appId: '1:487120249063:android:d5d6535b4ddbe5979c8242',
    messagingSenderId: '487120249063',
    projectId: 'iedcwebsite-6a1fc',
    storageBucket: 'iedcwebsite-6a1fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcRNUbE0M1DlTCEdql7mq4y4rW7p49RBY',
    appId: '1:487120249063:ios:350af8111d8ee9d29c8242',
    messagingSenderId: '487120249063',
    projectId: 'iedcwebsite-6a1fc',
    storageBucket: 'iedcwebsite-6a1fc.firebasestorage.app',
    iosClientId: '487120249063-k5fjq117aedfn6ruhhooi0nmp5gk4i0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.iedcWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcRNUbE0M1DlTCEdql7mq4y4rW7p49RBY',
    appId: '1:487120249063:ios:350af8111d8ee9d29c8242',
    messagingSenderId: '487120249063',
    projectId: 'iedcwebsite-6a1fc',
    storageBucket: 'iedcwebsite-6a1fc.firebasestorage.app',
    iosClientId: '487120249063-k5fjq117aedfn6ruhhooi0nmp5gk4i0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.iedcWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCouHnDlRq6UHVcfu67JqsHTXePohr1dDY',
    appId: '1:487120249063:web:a849d3fd23eec5679c8242',
    messagingSenderId: '487120249063',
    projectId: 'iedcwebsite-6a1fc',
    authDomain: 'iedcwebsite-6a1fc.firebaseapp.com',
    storageBucket: 'iedcwebsite-6a1fc.firebasestorage.app',
    measurementId: 'G-57KRND1JM9',
  );

}