// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3D8TOr9y5NMLkugJzucM2tUQYQOk9gc',
    appId: '1:598766714004:web:f6e727b5900fa3b2148881',
    messagingSenderId: '598766714004',
    projectId: 'iedcwebsite',
    authDomain: 'iedcwebsite.firebaseapp.com',
    storageBucket: 'iedcwebsite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKOeh9HcY38RcIvMjAFqwjrUacnWLJz0',
    appId: '1:598766714004:android:c4040d5c0d692af0148881',
    messagingSenderId: '598766714004',
    projectId: 'iedcwebsite',
    storageBucket: 'iedcwebsite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChyQ5wQtVopBGZ8-kmu8QJ2TLPhwB7Niw',
    appId: '1:598766714004:ios:3613001af96b56e3148881',
    messagingSenderId: '598766714004',
    projectId: 'iedcwebsite',
    storageBucket: 'iedcwebsite.firebasestorage.app',
    iosBundleId: 'com.example.iedcWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChyQ5wQtVopBGZ8-kmu8QJ2TLPhwB7Niw',
    appId: '1:598766714004:ios:3613001af96b56e3148881',
    messagingSenderId: '598766714004',
    projectId: 'iedcwebsite',
    storageBucket: 'iedcwebsite.firebasestorage.app',
    iosBundleId: 'com.example.iedcWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM3D8TOr9y5NMLkugJzucM2tUQYQOk9gc',
    appId: '1:598766714004:web:186c9d624c0f9959148881',
    messagingSenderId: '598766714004',
    projectId: 'iedcwebsite',
    authDomain: 'iedcwebsite.firebaseapp.com',
    storageBucket: 'iedcwebsite.firebasestorage.app',
  );
}
