import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:iedc_web/homepage.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire configure


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with options for the current platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const HomePage());
}
